# Exam packs: (title, "a,b,c", [mc×3], [open×2])
# mc = (legend, [opt_a, opt_b, opt_c, opt_d], feedback)
# open = (question, answer_html)

M3C1 = [
    ("Refractores y reflectores", "b,b,b",
     [("Un telescopio refractor concentra la luz principalmente mediante:",
       ["Espejos curvos", "Lentes que refractan la luz", "Difracción en la atmósfera", "Interferencia destructiva"],
       "La transcripción dice «difracción»; físicamente es refracción en el vidrio."),
      ("La principal ventaja de un reflector newtoniano sobre un refractor grande es:",
       ["Mayor aberración cromática", "Poder soportar el espejo por detrás y escalar el diámetro", "No necesita revestimiento", "Campo de visión más amplio sin corrección"],
       "El soporte posterior permite espejos más grandes sin flexionar el vidrio solo por los bordes."),
      ("En un diseño Cassegrain la luz del espejo primario:",
       ["Sale por un lateral sin obstáculo", "Rebota en secundario y pasa por orificio central", "Atraviesa el espejo sin reflejar", "Solo funciona en radio"],
       "El orificio central es pequeño comparado con el área del espejo.")],
     [("Explica por qué los refractores históricos (Yerkes) tenían tubos tan largos.",
       "Largo focal suave reduce la concentración rápida de la luz y mitiga la <strong>aberración cromática</strong> (arcoíris en el foco). Tubos de 12–18 m eran el precio de recolectar mucha luz con lentes."),
      ("¿Qué problema comparten refractores y lentes dentro de instrumentos modernos como Gaia?",
       "La <strong>dispersión cromática</strong>: objetos rojos y azules no foculan exactamente igual → posiciones astrométricas espurias que deben corregirse cuando la precisión es de microarcosegundos.")]),
    ("Área colectora", "c,b,c",
     [("Si un objeto está al triple de distancia, su flujo observado es aproximadamente:",
       ["Un tercio", "La mitad", "Un noveno", "Igual"],
       "Flujo ∝ 1/d² → (1/3)² = 1/9."),
      ("La motivación principal para construir telescopios cada vez más grandes es:",
       ["Ver colores más vivos", "Recolectar más fotones en el mismo tiempo", "Evitar la atmósfera", "Reducir el seeing a cero"],
       "Más área colectora compensa la dilución por distancia."),
      ("El espejo primario de un telescopio de 8 m recolecta respecto a uno de 1 m:",
       ["8 veces más luz", "16 veces", "64 veces (área ∝ D²)", "512 veces"],
       "Área = π(D/2)² → ratio (8/1)² = 64.")],
     [("Relaciona la ley del inverso del cuadrado con la «carrera» por telescopios grandes.",
       "Objetos lejanos entregan pocos fotones por unidad de área. Duplicar el diámetro cuadruplica el área y, en ingeniería de señales, mejora el S/N como √N si el ruido es de fondo."),
      ("¿Por qué un animal nocturno evoluciona ojos grandes?",
       "Necesita <strong>mayor pupila</strong> (área colectora) para detectar pocos fotones en poco tiempo — mismo principio físico que los astrónomos persiguen con espejos de metros.")]),
    ("Óptica activa", "a,b,b",
     [("La óptica activa corrige principalmente:",
       ["La deformación del espejo al cambiar la orientación del telescopio", "La turbulencia atmosférica en milisegundos", "El redshift cosmológico", "La rotación de la Tierra"],
       "Pistones en el espejo (~cada minuto), no la atmósfera (eso es OA)."),
      ("En Gemini 8 m, el espejo es más delgado que en Palomar porque:",
       ["Se usa plástico", "Se acepta flexión y se corrige con pistones", "No hay gravedad en la cúpula", "Es un refractor"],
       "Rendirse a la rigidez perfecta y corregir activamente."),
      ("La estrella guía en óptica activa sirve para:",
       ["Medir temperatura", "Detectar si la imagen se desenfoca y reajustar pistones", "Calibrar el láser de sodio", "Medir redshift"],
       "Si la estrella deja de ser un puntito → recorregir forma del espejo.")],
     [("Diferencia óptica activa y óptica adaptativa en tiempos y qué corrigen.",
       "<strong>Activa:</strong> forma del espejo, pistones, ~1 min, gravedad/flexión del instrumento. <strong>Adaptativa:</strong> atmósfera, espejo deformable secundario, ms–s, láser en capa de sodio."),
      ("¿Por qué Palomar 5 m fue un límite práctico para espejos monolíticos?",
       "Mantener rigidez y mover toneladas de estructura escala mal; más diámetro → mucho más masa de soporte y actuadores.")]),
    ("Espejos segmentados", "b,b,b",
     [("Keck usa espejos segmentados principalmente para:",
       ["Evitar revestir con aluminio", "Permitir espejos más delgados y livianos por segmento", "Observar solo en radio", "Eliminar el seeing"],
       "Cada segmento ~7,5 cm grosor; el problema es alinearlos."),
      ("El reto computacional histórico de Keck era:",
       ["Imprimir las imágenes", "Alinear decenas de segmentos cada ~minuto", "Enfriar el detector", "Sincronizar con GPS"],
       "Matriz gigante de grados de libertad; en los 80 era caro, hoy trivial."),
      ("El ELT combina:",
       ["Solo refractores", "Segmentación + óptica activa + láseres para OA", "Solo placas fotográficas", "Un único espejo de 1 m"],
       "40 m segmentado con OA en cada segmento y multi-láser.")],
     [("¿Por qué dividir un espejo de 8 m en hexágonos?",
       "Un monolito más delgado se rompe o flexiona demasiado; segmentos permiten soporte local y pistones independientes, a costa de control activo continuo."),
      ("Menciona dos telescopios de ~10 m y dónde están.",
       "<strong>Keck I/II</strong> en Mauna Kea (Hawái); también GTC ~10,2 m en Islas Canarias. Ambos usan segmentación o variantes avanzadas.")]),
    ("Vera Rubin", "b,c,b",
     [("El telescopio Vera Rubin se distingue por:",
       ["Ser el más pequeño en Chile", "Campo de visión enorme (~3,5°) y cámara gigapixel", "Observar solo en rayos gamma", "No usar espejos"],
       "Survey de todo el cielo visible repetidamente."),
      ("La cámara de Vera Rubin tiene aproximadamente:",
       ["32 megapíxeles", "320 megapíxeles", "3,2 gigapíxeles", "3,2 terapíxeles"],
       "3,2 Gpx; terabytes por noche."),
      ("El espejo de Vera Rubin es especial porque:",
       ["Es de plástico", "Combina curvaturas primaria y terciaria en un solo elemento", "No refleja luz", "Mide neutrinos"],
       "Tres reflexiones en camino óptico compacto; instrumentos arriba.")],
     [("Compara el campo de Hubble con el de Vera Rubin.",
       "Hubble: minúsculo (orden del tamaño de un alfiler en el cielo). Vera Rubin: ~3,5° ≈ 40 diámetros lunares — diseñado para <em>surveys</em> sin apuntar objeto a objeto."),
      ("¿Qué volumen de datos espera Vera Rubin por noche y por qué?",
       "Del orden de <strong>terabytes/noche</strong>: imágenes de 3,2 Gpx cada pocos minutos durante toda la noche → problema de big data (tema del módulo II).")]),
    ("Límite de difracción", "a,c,b",
     [("El tamaño del disco de Airy escala como:",
       ["1,22 λ/D", "D/λ", "λ·D²", "1/D sin λ"],
       "θ ≈ 1,22 λ/D en radianes."),
      ("Con λ fija, un telescopio más grande produce un disco de difracción:",
       ["Más grande", "Igual", "Más pequeño", "Inexistente"],
       "θ ∝ 1/D."),
      ("Dos estrellas separadas por menos que θ de Airy:",
       ["Se resuelven fácilmente", "Pueden verse como una sola", "Desaparecen", "Emiten radio"],
       "Convolutión de dos patrones de Airy.")],
     [("Escribe la fórmula del límite de difracción y explica cada símbolo.",
       "θ ≈ 1,22 λ/D: λ longitud de onda observada, D diámetro del telescopio, θ tamaño angular mínimo resoluble (primer mínimo del patrón de Airy)."),
      ("¿Por qué Galileo dibujó Saturno tan mal comparado con Hubble?",
       "Telescopio pequeño → θ grande → baja resolución; no podía separar anillos y disco con claridad (inferencia histórica ilustrada en clase).")]),
    ("Seeing atmosférico", "b,b,c",
     [("El «seeing» se refiere a:",
       ["La rotación del telescopio", "La degradación de imagen por turbulencia atmosférica", "La eficiencia del CCD", "El láser de calibración"],
       "Corrección de transcripción: «zinc/SIG» → seeing."),
      ("En un buen sitio chileno el seeing puede ser del orden de:",
       ["10 arcmin", "0,6–1 arcsec", "0,001 arcsec", "1 grado"],
       "0,6″ es excelente; mucho mejor que sitios húmedos."),
      ("El seeing típicamente es respecto al límite de difracción en óptico desde tierra:",
       ["Más pequeño", "Comparable", "Mucho mayor (domina la imagen)", "Irrelevante"],
       "Atmósfera desparrama más que el disco de Airy de un 8 m.")],
     [("Explica por qué Chile es privilegiado para observación óptica.",
       "Cielo oscuro, pocas nubes, <strong>baja turbulencia</strong> y capas atmosféricas estables → seeing bajo → imagen más nítida que en sitios húmedos o urbanos."),
      ("¿Qué es el «titilar» de las estrellas y su causa física?",
       "Variación de intensidad por <strong>células de turbulencia</strong> que desvían rayos (como lentes cambiantes); no es que la estrella parpadee intrínsecamente.")]),
    ("Óptica adaptativa", "c,a,b",
     [("La óptica adaptativa usa frecuentemente:",
       ["Placas fotográficas", "Solo filtros de color", "Láser que excita sodio en la atmósfera", "Neutrinos"],
       "Estrella artificial para medir deformación del frente de ondas."),
      ("La corrección adaptativa ocurre en escalas de tiempo:",
       ["Milisegundos a segundos", "Una vez por año", "Solo de día", "Horas sin cambio"],
       "La atmósfera cambia rápido; no se puede mover el espejo primario de 8 m así."),
      ("Las órbitas estelares en Sgr A* requirieron:",
       ["Solo placas del siglo XIX", "Óptica adaptativa en Keck para resolver estrellas", "Detectores de radio únicamente", "Ojo humano"],
       "Sin OA el centro galáctico es un borrón.")],
     [("Describe el flujo: láser → medida → corrección en OA.",
       "Láser ioniza Na a ~90 km → punto brillante; si se deforma, hay aberración atmosférica; espejo deformable (o WFS) contrarresta antes del detector científico."),
      ("¿Por qué no se usa OA en todas las observaciones cada noche?",
       "Específica de ciertos instrumentos/objetivos; láser potente, riesgo aviación, costo; mucha ciencia (espectroscopía de galaxias lejanas) no la necesita.")]),
    ("Monturas y espejos", "a,b,b",
     [("El Mirror Lab en Arizona fabrica espejos:",
       ["Fundiendo vidrio en centrífuga y enfriando lentamente", "Pegando espejos de baño", "Solo con impresión 3D", "Importándolos de Yerkes"],
       "Rotación mantiene curvatura líquida; meses de enfriamiento."),
      ("El revestimiento de espejos ópticos típicamente usa:",
       ["Cobre o hierro", "Aluminio o plata (capas atómicas)", "Pintura latex", "Agua"],
       "Evaporación en vacío; JWST usa oro para IR."),
      ("La montura alt-azimutal de muchos telescopios modernos:",
       ["No puede apuntar al cielo", "Rota en azimut e inclina en elevación", "Solo funciona de día", "Reemplaza el detector"],
       "Más compacta que ecuatorial clásica; requiere rotación de campo.")],
     [("¿Qué pasó con el espejo de Gemini al túnel en Tololo?",
       "El espejo de 8 m no cabía; hubo que modificar el túnel — ejemplo de logística de infraestructura olvidada en el diseño."),
      ("Compara Dupont (2,5 m) con Magallanes (6,5 m) en Las Campanas.",
       "Misma tecnología reflectora Cassegrain; Magallanes usa <strong>óptica activa</strong> y espejo más delgado; estructura relativamente más compacta que la escala de Palomar.")]),
    ("Integrador clase 1", "b,b,b",
     [("Este módulo III se enfoca en:",
       ["Solo teoría de cuerpos negros", "Técnicas de observación y tecnologías que las habilitan", "Exclusivamente cosmología", "Matemática pura"],
       "Cinco clases: telescopios, detectores, radio/HE, GW/neutrinos, futuro."),
      ("La clase 1 NO cubrió en detalle:",
       ["Monturas de telescopios", "Detectores CCD (eso es clase 2)", "Óptica activa", "Vera Rubin"],
       "Detectores → clase 2."),
      ("El próximo límite tras espejos flexibles segmentados de 8–10 m fue:",
       ["Volver a refractores", "Espejos segmentados + control activo (Keck, ELT)", "Solo observación con ojo", "Telescopios submarinos"],
       "Segmentación habilitó 10 m y planifica 40 m.")],
     [("Resume la evolución tecnológica: refractor → monolito → activo → segmentado.",
       "Refractor limitado por peso/cromatismo → reflector monolítico hasta ~5 m → óptica activa 6–8 m con pistones → segmentados 10–40 m con control matricial y OA."),
      ("Desde ingeniería: ¿qué tipo de problemas aparecen además de «óptica»?",
       "<strong>Estructural</strong> (rigidez, masa), <strong>materiales</strong> (vidrio, revestimiento), <strong>control</strong> (pistones, OA), <strong>logística</strong> (transporte, túneles), <strong>computación</strong> (alinear segmentos).")]),
]

M3C2 = [
    ("Placas fotográficas", "b,b,b",
     [("Las placas fotográficas astronómicas registran imagen mediante:",
       ["CCD digital", "Emulsión de plata que se oscurece con la luz", "Antenas de radio", "Efecto Compton"],
       "Vidrio + emulsión; precursor del detector integrador."),
      ("El Tololo Supernova Survey usó:",
       ["Solo satélites", "Placas + blink comparator para encontrar transientes", "LIGO", "Neutrinos"],
       "Blink alterna dos placas → supernovas."),
      ("Una limitación clave de las placas es:",
       ["No captan luz", "Saturación sin escala de brillo fina", "Solo funcionan en gamma", "Requieren láser"],
       "Zona negra = información perdida de luminosidad.")],
     [("¿Por qué digitalizar placas antiguas sigue siendo útil?",
       "Baselines de <strong>décadas</strong> para movimientos propios y variabilidad; el cielo cambia lentamente."),
      ("Menciona el proyecto «Carte du Ciel» y el rol de Chile.",
       "Atlas fotográfico del cielo; Chile aportó la parte <strong>austral</strong> — primer mapeo global con placas.")]),
    ("Efecto fotoeléctrico", "c,b,b",
     [("En el efecto fotoeléctrico, la energía del electrón emitido depende de:",
       ["La intensidad de la luz", "El área del metal", "La frecuencia (energía) del fotón", "La temperatura ambiente"],
       "E = hν − φ; Nobel Einstein 1921."),
      ("Si todos los fotones tienen energía bajo el umbral:",
       ["Más intensidad siempre libera electrones", "Ningún electrón sale por más fotones que lleguen", "El metal se derrite", "Aumenta la frecuencia sola"],
       "Cuantización: un fotón o nada."),
      ("El efecto fotoeléctrico es base de:",
       ["Telescopios de radio", "CCDs y paneles solares", "Solo placas", "Cherenkov"],
       "Fotón libera electrón en semiconductor.")],
     [("Contrasta comportamiento «onda» vs «partícula» en fotoeléctrico.",
       "Onda clásica esperaría acumulación de energía; se observa umbral por <strong>fotón</strong> → naturaleza cuántica de la luz."),
      ("Calcula orden de magnitud: ¿por qué hν debe superar φ?",
       "φ ~ eV típico en metales; visible hν ~ 1,5–3 eV; IR puede no liberar si φ es alto — depende del material.")]),
    ("Anatomía del CCD", "a,b,b",
     [("Un CCD acumula señal en cada píxel como:",
       ["Carga (electrones) en potenciales", "Agua literal", "Campos magnéticos estáticos", "Solo voltaje AC de la red"],
       "Analogía de baldes: fotones → carga atrapada."),
      ("La lectura típica de un CCD astronómico:",
       ["Paralela en todos los píxeles a la vez (CMOS típico celular)", "Serial: filas corridas al amplificador", "Solo una vez al año", "Por placas químicas"],
       "Cuello de botella: un amplificador (o pocos)."),
      ("El tamaño típico de un píxel CCD es del orden de:",
       ["1 metro", "10–20 micrómetros", "1 kilómetro", "1 nanómetro exacto"],
       "Nanotecnología: electrodos y aislantes microscópicos.")],
     [("Describe la analogía de los baldes y por qué es útil.",
       "Fotones = gotas; píxel = balde que acumula; corrimiento = transferir carga fila a fila hasta el «grifo» amplificador."),
      ("¿Qué pasa si falla la transferencia en un píxel intermedio?",
       "Se pierde toda la carga de esa columna aguas arriba → <strong>columna muerta</strong> en la imagen.")]),
    ("Eficiencia cuántica", "b,b,b",
     [("La eficiencia cuántica (EQ) mide:",
       ["Solo el precio del detector", "Fracción de fotones convertidos en electrón", "La velocidad del telescopio", "El seeing"],
       "Probabilidad de detección por fotón."),
      ("Aproximadamente, la EQ de un buen CCD en óptico puede ser:",
       ["1%", "Hasta ~90%", "200%", "Cero siempre"],
       "Mucho mayor que el ojo (~1% pico)."),
      ("El ojo humano es menos eficiente que un CCD principalmente porque:",
       ["No tiene retina", "Menor EQ y menor integración controlada", "Usa solo radio", "Tiene demasiados píxeles"],
       "Evolución biológica vs. ingeniería de silicio.")],
     [("¿Por qué la curva EQ es función de λ?",
       "Longitud de absorción en silicio crece con λ; grosor del chip y material determinan qué fotones se absorben y generan pares e⁻-h⁺."),
      ("Compara placas, ojo y CCD en eficiencia y calibración.",
       "Placas/ojo: baja EQ, respuesta no lineal, saturación. CCD: alta EQ, digital, calibrable con flats/darks.")]),
    ("Lectura y bits", "b,b,b",
     [("Un CCD astronómico típico usa más bits por píxel que un JPG porque:",
       ["El monitor lo exige", "Necesita mayor rango dinámico (objetos brillantes y débiles juntos)", "JPG tiene más bits", "Las estrellas lo prohíben"],
       "16–64 bits vs 8 bits en pantalla."),
      ("Con 16 bits el valor máximo por píxel es:",
       ["255", "65535", "16", "2"],
       "2¹⁶ − 1 = 65535."),
      ("El amplificador del CCD:",
       ["Solo enfría el chip", "Convierte carga en número digital", "Reemplaza el telescopio", "Emite rayos gamma"],
       "Lectura serial de voltaje proporcional a electrones.")],
     [("Explica saturación a 65535 ADU con un flat brillante.",
       "Más electrones de los que caben en el rango del ADC → todos se clipean al máximo → pérdida de información de gradiente."),
      ("¿Por qué Vera Rubin necesita lectura en ~2 s para 3,2 Gpx?",
       "Si leer demora minutos, pierdes tiempo de <em>observar</em> el cielo; survey requiere ciclo observación-lectura rápido.")]),
    ("Overscan y dark", "a,a,b",
     [("El overscan consiste en:",
       ["Leer filas extra sin iluminación para medir bias/dark", "Ampliar el telescopio", "Usar solo luz laser", "Borrar rayos cósmicos automáticamente"],
       "Regiones sin ciencia pero con corriente residual."),
      ("Los CCD se enfrían con N₂ líquido principalmente para:",
       ["Reducir corriente oscura térmica", "Congelar al astrónomo", "Aumentar seeing", "Calibrar GPS"],
       "Menos electrones espurios por calor."),
      ("Si el overscan muestra ~1300 ADU sin luz:",
       ["El detector está roto necesariamente", "Hay offset/dark que debe restarse en calibración", "Es el valor de saturación", "Es señal extraterrestre"],
       "Bias/dark correction estándar.")],
     [("Diferencia bias, dark y flat en calibración CCD.",
       "<strong>Bias:</strong> offset electrónico cero exposición. <strong>Dark:</strong> térmica con obturador cerrado. <strong>Flat:</strong> respuesta relativa pixel a pixel con iluminación uniforme."),
      ("¿Por qué el header FITS importa tanto?",
       "Contiene BITPIX, dimensiones, tiempo, filtro, coordenadas — sin header los números del array pierden contexto físico.")]),
    ("Rayos cósmicos", "b,b,b",
     [("En superficie terrestre la tasa de rayos cósmicos es del orden de:",
       ["2 por km² por hora", "~2 por cm² por minuto", "Cero", "Uno por siglo"],
       "Partículas cargadas constantes; mutaciones en ADN posibles."),
      ("Un rayo cósmico en un CCD aparece típicamente como:",
       ["Línea espectral estrecha", "Mancha/raya brillante en pocos píxeles", "Oscurecimiento total", "Solo en radio"],
       "Ioniza silicio → varios electrones espurios."),
      ("La mitigación estándar es:",
       ["Una sola exposición larga", "Múltiples exposiciones y rechazar coincidencias", "No usar CCD", "Apagar el telescopio"],
       "Probabilidad de golpear el mismo píxel dos veces es baja.")],
     [("¿Por qué exposiciones >30 min pueden ser problemáticas?",
       "Acumulas muchos RC → imagen llena de rayas → difícil extraer ciencia del espectro/objeto."),
      ("Relaciona RC con ingeniería de confiabilidad.",
       "Eventos aleatorios de alta energía = <strong>ruido impulsivo</strong>; mitigación por redundancia temporal (median stack, sigma clip).")]),
    ("Calibración y artefactos", "b,a,b",
     [("Un flat field sirve para:",
       ["Medir posición de estrellas solo", "Corregir sensibilidad distinta píxel a píxel", "Aumentar el seeing", "Detectar neutrinos"],
       "Iluminación uniforme conocida → mapa de ganancias."),
      ("Una columna muerta ocurre cuando:",
       ["Falla un píxel y pierde carga de toda la columna", "Hay demasiadas estrellas", "El láser está encendido", "Es de noche"],
       "Aislante dañado → fuga de electrones en transferencia."),
      ("El dithering (mover ligeramente el telescopio) ayuda a:",
       ["Empeorar la imagen", "Rellenar huecos de píxeles/columnas malas", "Aumentar RC", "Apagar el CCD"],
       "Varias posiciones → combinar y recuperar área.")],
     [("Describe el flujo bias → dark → flat → ciencia.",
       "Restar bias/dark; dividir por flat normalizado; aplicar a imagen científica para flujo y forma flat."),
      ("¿Qué es un echelle y por qué la imagen parece «franjas»?",
       "Espectrógrafo de alto orden; cada franja = rango λ distinto superpuesto en el CCD 2D.")]),
    ("Vera Rubin CCD", "b,b,b",
     [("La cámara Vera Rubin usa aproximadamente:",
       ["1 CCD", "200 CCD en paralelo", "Solo placas", "Antenas de 40 m"],
       "Mosaico masivo para 3,2 Gpx."),
      ("Cada CCD de Vera Rubin tiene del orden de:",
       ["16 píxeles", "16 megapíxeles", "16 gigapíxeles", "16 bytes"],
       "16 Mpx × 200 ≈ 3,2 Gpx."),
      ("Múltiples amplificadores por chip permiten:",
       ["Lectura más lenta", "Lectura más rápida en paralelo", "Eliminar calibración", "Ver neutrinos"],
       "Trade-off: más ruido de lectura si muy rápido.")],
     [("Compara Mage (Las Campanas) turbo vs Vera Rubin.",
       "Mage ~2048² en 14 s turbo; Vera Rubin 3,2 Gpx en ~2 s — salto de ingeniería en paralelización."),
      ("¿Por qué distintos chips tienen colores distintos en fotos del focal plane?",
       "Fabricados por empresas distintas; pequeñas diferencias de EQ → corregir en calibración.")]),
    ("Detectores infrarrojos", "a,a,b",
     [("Los detectores IR de JWST/NIRCam difieren del CCD clásico porque:",
       ["Cada píxel puede leerse con su propia electrónica / lectura diferencial", "No usan fotoeléctrico", "Funcionan a 1000 K", "Son placas de plata"],
       "Lectura de tasa dQ/dt; overscan con píxeles físicamente tapados."),
      ("En IR es crítico aislar fuentes de calor porque:",
       ["El calor emite fotones IR que confunden la señal", "El frío daña el espejo", "No hay atmósfera", "Los láseres se apagan"],
       "Cualquier objeto cálido brilla en IR."),
      ("NIRCam combina chips para:",
       ["Solo una longitud de onda", "Distintos rangos λ (corto y largo) en el plano focal", "Rayos gamma", "Solo polarización"],
       "8 chips corto λ + 2 largo λ; gaps entre módulos.")],
     [("Explica overscan «físico» en IR vs serial en CCD.",
       "Píxeles en borde <strong>tapados con metal</strong>; se leen igual para estimar dark sin iluminación, sin corrimiento de filas."),
      ("¿Por qué JWST observa principalmente en IR?",
       "Galaxias alto z: corrimiento al rojo empuja líneas UV/visible a IR; además IR penetra polvo en formación estelar.")]),
]

M3C3 = [
    ("Espectro y atmósfera", "b,b,b",
     [("La atmósfera es muy transparente en:",
       ["Solo rayos gamma", "Óptico visible y banda radio", "Todo el IR sin excepción", "Ninguna banda"],
       "Ventanas clásicas; UV/X bloqueados (protección)."),
      ("ALMA está en Atacama principalmente por:",
       ["Turismo", "Baja humedad (menos absorción por H₂O en sub-mm)", "Cerca del mar", "Ver auroras"],
       "Líneas de agua en atmósfera opacan sub-mm."),
      ("Observar UV desde tierra es difícil porque:",
       ["No hay estrellas UV", "La atmósfera es opaca a UV", "Los CCD no existen", "Solo de día"],
       "Motivo para telescopios espaciales (HST, etc.).")],
     [("¿Por qué no es casualidad que nuestros ojos vean el óptico?",
       "Ventana atmosférica coincide con λ donde Sol emite más; evolutivamente útil (inferencia razonable de clase)."),
      ("Menciona dos motivos para poner telescopios en el espacio.",
       "Evitar absorción/scattering atmosférico (UV, IR, X); eliminar seeing para óptico/UV.")]),
    ("Antenas dipolo", "a,b,c",
     [("En una antena dipolo la señal se genera porque:",
       ["El campo eléctrico de la onda mueve electrones en el conductor", "Los fotones se reflejan en espejo parabólico", "Ocurre fusión nuclear", "Hay CCD"],
       "Oscilación EM → corriente alterna medible."),
      ("Jansky (1932) usó antenas para:",
       ["Televisión", "Primera detección astronómica de radio del cielo", "Medir neutrinos", "GPS"],
       "Inicio de la radioastronomía."),
      ("Las antenas SKA pathfinder tipo «cerca» son:",
       ["Espejos de 40 m", "Cables/dipolos sobre aislante", "Solo placas", "Detectores Cherenkov"],
       "Tecnología simple pero efectiva a bajas frecuencias.")],
     [("Contrasta antena dipolo vs plato parabólico.",
       "Dipolo: captura en λ ~ longitud del cable; parabólico: foco concentra ondas planas coherentes."),
      ("¿Por qué Bell detectó púlsares con antena «rústica»?",
       "Señales de radio fuertes y periódicas; no hace falta imagen fina para descubrir periodicidad.")]),
    ("Plato parabólico", "b,b,b",
     [("La forma parabólica garantiza que ondas planas lleguen al foco:",
       ["Con distintas fases aleatorias", "Con la misma fase (constructiva)", "Sin amplitud", "Solo en gamma"],
       "Igual camino óptico → coherencia."),
      ("Si la antena apunta lejos del objeto:",
       ["La señal aumenta", "Interferencia parcial/destructiva reduce señal", "No cambia nada", "Detecta neutrinos"],
       "Caminos distintos → desfase."),
      ("En radio, a diferencia del óptico «fotón a fotón», importa mucho:",
       ["Solo el color del cúpula", "La coherencia de fase de la onda", "La masa del astrónomo", "El día juliano"],
       "Suma amplitud de campos, no solo potencia incoherente.")],
     [("Explica interferencia constructiva con dos ondas en fase.",
       "Amplitudes se suman → señal más fuerte en detector; en antena eso significa fuente en la dirección apuntada."),
      ("Analogía con cancelación de ruido en audífonos.",
       "Generan onda desfasada π para cancelar — mismo principio de superposición, signo opuesto.")]),
    ("Resolución en radio", "b,a,b",
     [("La resolución angular de una antena θ ≈ 1,22 λ/D con D=40 m y λ~2 cm da del orden de:",
       ["0,01 arcsec", "Minutos a cientos de arcsec", "90 grados", "Cero"],
       "~125 arcsec en ejemplo de clase."),
      ("Radio tiene peor resolución que óptico a igual D porque:",
       ["λ es mucho mayor", "Las antenas son de madera", "No hay atmósfera", "λ es menor"],
       "θ ∝ λ/D; λ radio ~ cm vs nm."),
      ("Un buen seeing en Chile en óptico es ~0,6″; comparado con radio 40 m:",
       ["Radio siempre mejor", "Óptico puede ser cientos de veces más fino", "Iguales", "No comparables"],
       "125″ vs 0,6″.")],
     [("Calcula conceptualmente por qué FAST 500 m aún da ~50″.",
       "λ ~ 10 cm → θ ~ 1,22×0,1/500 rad ≈ orden decenas de arcsec; área grande no estrecha el haz si λ es grande."),
      ("¿Qué ganas con plato grande en radio single-dish?",
       "<strong>Sensibilidad</strong> (más área recolectora), no necesariamente resolución fina.")]),
    ("Interferometría básica", "b,b,b",
     [("En interferometría el «diámetro» efectivo para resolución es:",
       ["Solo el radio del plato individual", "La separación máxima entre antenas (baseline)", "La altitud del sitio", "El diámetro de la Tierra siempre"],
       "B puede ser km → θ muy pequeño."),
      ("Con solo dos antenas la imagen tiene:",
       ["Resolución perfecta", "Ambigüedades (franjas, elongación)", "Cero señal", "Solo colores"],
       "No puedes localizar únicamente en una dirección."),
      ("El correlador:",
       ["Solo enfría fibra", "Combina señales midiendo fase relativa", "Reemplaza espejo", "Es un CCD"],
       "Corazón digital de ALMA/EHT.")],
     [("¿Por qué ALMA tiene posiciones fijas para antenas?",
       "Fibra óptica de longitud conocida → control de fase; mover antena = cambiar baseline calibrada."),
      ("Trade-off área vs resolución en interferómetro.",
       "Resolución ~ λ/B grande; sensibilidad ~ área total de antenas (suma de platos), no del disco B.")]),
    ("ALMA y correlador", "b,b,a",
     [("ALMA opera principalmente en:",
       ["Solo FM radio", "Milímetro y submilímetro", "Rayos gamma", "Neutrinos"],
       "λ ~ 0,3 mm a mm; requiere sitio seco."),
      ("La línea de base máxima de ALMA es del orden de:",
       ["1 metro", "16 km", "1 AU", "Un parsec"],
       "Antenas transportables entre pads."),
      ("El correlador de ALMA está en alta montaña porque:",
       ["Históricamente procesaba en sitio (upgrade mueve parte)", "Cerca de antenas; datos masivos", "Para ver nubes", "No existe"],
       "Procesamiento HPC de miles de correlaciones; ahora upgrade en menor altitud.")],
     [("¿Qué muestra ALMA en discos protoplanetarios?",
       "Estructura de polvo/gas a resolución fina → formación planetaria; revolucionario vs single-dish borroso."),
      ("¿Por qué agregar más antenas mejora la imagen?",
       "Más pares → más frecuencias espaciales muestreadas → menos ambigüedad (síntesis tipo Fourier).")]),
    ("EHT y VLBI", "b,b,b",
     [("El EHT combina telescopios mediante:",
       ["Fibra entre continentes en tiempo real", "Grabación sincronizada y correlación offline", "Solo un plato", "Ojo humano"],
       "VLBI: discos duros + timestamps ultra precisos."),
      ("La línea de base del EHT es del orden de:",
       ["1 cm", "Diámetro de la Tierra (~8000 km)", "1 m", "Un año luz"],
       "Máxima separación posible en Tierra."),
      ("La imagen de M87* requirió:",
       ["Una foto con celular", "Petabytes y correlación posterior", "Solo teoría", "Una noche sin datos"],
       "Femtosegundos de muestreo × muchas estaciones.")],
     [("¿Por qué no hay fibra óptica entre telescopios del EHT?",
       "Distancias intercontinentales; se graba señal local y se correlaciona después con relojes atómicos (H-maser, etc.)."),
      ("Relaciona EHT con límite de difracción pero en radio/mm.",
       "Mismo θ ~ λ/B; B enorme compensa λ mm para ver sombra de BH.")]),
    ("Alta energía", "a,b,b",
     [("En rayos X/gamma no se usa espejo reflector clásico porque:",
       ["λ es demasiado corta; fotones atraviesan materiales", "No hay fotones", "Solo hay ondas de radio", "La atmósfera amplifica"],
       "λ ~ separación atómica → no refracción/reflexión útil."),
      ("Compton scattering detecta:",
       ["Solo neutrinos", "Electrones liberados tras choque con fotón de alta energía", "Ondas de gravedad", "Solo placas"],
       "Intercambio energía-momento fotón-e⁻."),
      ("Fermi-LAT en 7 años detectó del orden de:",
       ["7 fotones", "700 000 fotones gamma", "Infinitos", "Cero"],
       "Pocos eventos → mapas de conteo, no imágenes CCD densas.")],
     [("Contrasta detección óptica vs gamma.",
       "Óptico: millones de fotones/s en CCD. Gamma: conteo raro evento a evento; telescopio = cámara de trazas."),
      ("¿Por qué cristales densos para Compton?",
       "Alta probabilidad de interacción con electrones de valencia en grilla ordenada.")]),
    ("Cherenkov y CTA", "a,b,b",
     [("Radiación Cherenkov ocurre cuando:",
       ["Una partícula viaja más rápido que la luz en el medio (c/n)", "Hay eclipse", "El CCD satura", "Solo en vacío más rápido que c"],
       "Cono de luz azul; no viola SR (c del vacío es el límite)."),
      ("Los telescopios CTA detectan:",
       ["Rayos gamma directamente con CCD", "Flash óptico breve de lluvia atmosférica por γ", "Solo radio FM", "Neutrinos"],
       "Cascada en atmósfera → Cherenkov → espejos al desierto."),
      ("Los detectores CTA miden:",
       ["Solo posición", "Posición y tiempo de llegada (ns) para reconstruir dirección", "Solo magnitud", "Polarización únicamente"],
       "Grilla de fotodetectores con cronometraje.")],
     [("Describe la cascada atmosférica iniciada por un γ.",
       "γ interactúa → pares e⁺e⁻ y hadrones → partículas superlumínicas en aire → conos Cherenkov → flash detectable."),
      ("¿Por qué CTA necesita espejos grandes y abiertos?",
       "Flash de ns; hay que recolectar mucha luz Cherenkov en ventana breve; muchos telescopios en array.")]),
    ("Multibanda integrador", "b,b,b",
     [("El centro de la Vía Láctea visto en radio (HI) muestra:",
       ["Igual que en gamma", "Estructura angosta del disco de gas", "Nada", "Solo estrellas jóvenes"],
       "HI en disco delgado → mapa estrecho."),
      ("Combinar bandas EM es necesario porque:",
       ["Una sola banda basta siempre", "Cada λ revela procesos físicos distintos", "Es ilegal no hacerlo", "Solo por estética"],
       "Dust, gas, estrellas, AGN brillan distinto."),
      ("Próxima clase del módulo incluirá:",
       ["Solo más placas", "Ondas gravitacionales y neutrinos", "Solo óptica", "Nada nuevo"],
       "Mensajeros no electromagnéticos.")],
     [("Compara FAST vs ALMA en ciencia.",
       "FAST: sensible, baja resolución, single dish. ALMA: interferometría, alta resolución en mm, menos área total."),
      ("Resume en una frase por qué la astronomía es «multimessenger» hoy.",
       "EM multibanda + GW + neutrinos + rayos cósmicos dan vistas complementares del mismo universo.")]),
]
